### Variables

@contentType = application/json

# @name encontrandoTodosOsPortifolios
GET {{baseUrl}}/portifolio HTTP/1.1
content-type: {{contentType}}
###

@portifolioId = {{criandoPortifolio.response.body.$.id}}

# @name encontrandoUmUnicoPortifolio
GET {{baseUrl}}/portifolio/1 HTTP/1.1
content-type: {{contentType}}
###
# @name criandoPortifolio
POST {{baseUrl}}/portifolio HTTP/1.1
content-type: {{contentType}}

{
    "title": "Meu primeiro projeto ",
    "description": "portifolio criado em nodejs e mongodb",
    "message": "success"
}

###


 