### Variables

@contentType = application/json

# @name encontrandoTodosOsPortifolios
GET {{baseUrl}}/portifolio HTTP/1.1
content-type: {{contentType}}
###

@portifolioId = {{criandoPortifolio.response.body.$.slug}}

# @name encontrandoUmUnicoPortifolio
GET {{baseUrl}}/portifolio/meu-primeiro-projeto-4 HTTP/1.1
content-type: {{contentType}}
###
# @name criandoPortifolio
POST {{baseUrl}}/portifolio HTTP/1.1
content-type: {{contentType}}

{
    "title": "Meu primeiro projeto 4",
    "description": "portifolio criado em nodejs e mongodb",
    "message": "success"
}

###
PATCH  {{baseUrl}}/portifolio/meu-primeiro-projeto-4 HTTP/1.1
content-type: {{contentType}}

{
    "title": "Meu primeiro projeto alterado 00 ",
    "description": "portifolio criado em nodejs e mongodb",
    "message": "success"
}

###


DELETE   {{baseUrl}}/portifolio/meu-primeiro-projeto-4 HTTP/1.1
content-type: {{contentType}}




 